// Windows: hide console window in release builds (GUI mode only)
#![cfg_attr(all(not(debug_assertions), windows), windows_subsystem = "windows")]

mod config;
mod ping;
mod gui;
mod excel;
mod utils;

use slint::include_modules;
use std::rc::Rc;
use std::cell::RefCell;
use gui::app::PingTestApp;

fn main() {
    // Init logging
    let _ = env_logger::Builder::from_env(
        env_logger::Env::default().default_filter_or("info")
    ).format_timestamp_millis().try_init();

    log::info!("PingTest starting (Slint GUI)...");

    // Include the slint UI (generated by slint-build from app.slint)
    let (ui, _) = include_modules!();

    // Create app state
    let app = Rc::new(RefCell::new(PingTestApp::new()));

    // Create main window
    let window = MainWindow::new(&ui);

    // Set up callbacks - each callback clones the Rc and captures the app
    let app_clone = app.clone();
    window.on_start_ping(move || {
        app_clone.borrow_mut().start_ping();
    });

    let app_clone = app.clone();
    window.on_stop_ping(move || {
        app_clone.borrow_mut().stop_ping();
    });

    let app_clone = app.clone();
    window.on_refresh_results(move || {
        app_clone.borrow_mut().refresh_ping();
    });

    let app_clone = app.clone();
    window.on_import_ips(move || {
        app_clone.borrow_mut().import_file();
    });

    let app_clone = app.clone();
    window.on_export_results(move || {
        app_clone.borrow_mut().export_results();
    });

    let app_clone = app.clone();
    window.on_insert_to_source(move || {
        app_clone.borrow_mut().export_to_source_excel();
    });

    window.on_open_settings(move || {});
    window.on_open_about(move || {});

    let app_clone = app.clone();
    window.on_close_settings(move || {
        app_clone.borrow_mut().close_settings();
    });

    let app_clone = app.clone();
    window.on_save_settings(move || {
        app_clone.borrow_mut().save_settings_from_window();
    });

    let app_clone = app.clone();
    window.on_reset_settings(move || {
        app_clone.borrow_mut().reset_settings();
    });

    window.on_ip_warning_continue(move || {
        // The app should have already set ip_warning_confirmed
    });
    window.on_ip_warning_cancel(move || {});

    let app_clone = app.clone();
    window.on_close_about(move || {});

    let app_clone = app.clone();
    window.on_sort_table(move |column| {
        app_clone.borrow_mut().sort_table(column);
    });

    // Store window weak reference in app for timer updates and UI property access
    {
        let mut app_mut = app.borrow_mut();
        app_mut.set_window(window.clone());
    }

    // Run the window
    window.run();
}